name: Generate JSDOCS
run-name: Action by @${{ github.actor }}
on: push
permissions:
  contents: write
jobs:
  jsdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build JSDOCS
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./assets/scripts
          recurse: true
          output_dir: ./out
